import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [{
      type: 'autogenerated',
      dirName: 'docs'
    }
  ],
  quickSidebar: [{
      type: 'autogenerated',
      dirName: 'quick'
    }
  ],
  courseSidebar: [
    'course/社区教程',
    'course/视频入门教程',
    'course/starbook/starbook',
  ],
  courseStarBookSidebar: [{
      type: 'autogenerated',
      dirName: 'course/starbook'
    }
  ],
  releaseSidebar: [{
      type: 'autogenerated',
      dirName: 'release'
    }
  ],
  supportusSidebar: [{
      type: 'autogenerated',
      dirName: 'supportus'
    }
  ],
  shareSidebar: [{
      type: 'autogenerated',
      dirName: 'share'
    }
  ],
};

export default sidebars;
